name: ci

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/openwebui
      - name: Pull and Recreate Container
        uses: appleboy/ssh-action@v1.2.0
        with:
            host: ${{ envs.REMOTE_HOST }}
            username: ${{ secrets.REMOTE_USER }}
            key: ${{ secrets.SSH_KEY }}
            script: docker compose -f /opt/webui/docker-compose.yaml pull openwebui && docker compose -f /opt/webui/docker-compose.yaml up -d --force-recreate openwebui
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: karibu-labs-it
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://img.icons8.com/ios-filled/50/github.png
          SLACK_MESSAGE: "New version of Open WebUI https://hub.docker.com/repository/docker/karibu/openwebui/general :rocket:"
          SLACK_TITLE: New image version of Open WebUI
          SLACK_USERNAME: github-actions
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}